# fly.toml app configuration file generated for twkbackend on 2023-07-24T04:49:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twkbackend"
primary_region = "dfw"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
